export default [
    "You are so amazing just the way you are, never change",
    "I love your smile and seeing you laugh, it makes my day",
    "You are so beautiful inside and out",
    "You are a ray of sunshine in my life",
    "You always make me laugh and smile",
    "You are so thoughtful and kind.",
    "You're always so sweet and caring, it makes me feel special",
    "You are my best friend and I cherish our time together",
    "I admire all your hard work and dedication in all you do",
    "I love how considerate you are of others",
    "You make me a better person, and everyday I try to be better for you",
    "I love love love you so much more than you know",
    "Your smile is my favorite sunrise.",
    "You make even silence feel like a love song.",
    "You laugh like sunlight through leaves—soft, warm, and perfect.",
    "You’re the calm in every storm I didn’t know I needed.",
    "When you speak, the world softens to listen.",
    "Every time I see you, it feels like the first time all over again.",
    "You give ordinary days an extraordinary glow.",
    "You're my favorite place to come home to.",
    "You look like you were painted by someone who loves you deeply.",
    "Even time seems to pause to admire you.",
    "You’re the poem my heart didn’t know how to write.",
    "I see galaxies in your eyes when you look at me.",
    "You make existing feel magical.",
    "You make me believe that some people are made of stars.",
    "If I could bottle the feeling of holding you, I’d live in it forever.",
    "Every moment with you feels like a secret between my soul and the universe.",
    "You have the kind of beauty that makes flowers jealous.",
    "You make love feel like a quiet, steady miracle.",
    "Even your quirks are my favorite parts of the universe.",
    "The way you love makes me want to be the best version of myself.",
    "You’re my favorite part of every story I tell.",
    "You are the softest chapter in the book of my life.",
    "You are the reason I smile when no one’s watching.",
    "Your kindness is the language my heart has always spoken.",
    "Being with you is like dancing in a dream I never want to end.",
    "You laugh in colors, and I never want to see in black and white again.",
    "You are the sunrise I look forward to every morning.",
    "When you hold my hand, even gravity feels optional.",
    "You make the ordinary feel like a fairytale.",
    "You are my favorite kind of forever.",
    "Even the stars envy the way you shine.",
    "You’re the reason I look forward to tomorrow.",
    "You hug like home.",
    "You’re every love letter I’ve never written.",
    "You are my safe space in this chaotic world.",
    "You make love feel like breathing—natural, constant, and essential.",
    "Even in a crowded room, my heart looks for you.",
    "You make time slow down with just a glance.",
    "You're the melody that plays in the background of my happiest thoughts.",
    "You make the world a little softer, a little kinder."
];
